# Usa una versión oficial de Python optimizada para desarrollo
FROM python:3.12-slim

# Define el directorio de trabajo dentro del contenedor
WORKDIR /app

# Actualiza pip y añade dependencias básicas
RUN pip install --no-cache-dir --upgrade pip setuptools wheel rich

# Copia y instala dependencias del proyecto
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt