services:
  api_crud-dev:
    container_name: api_crud-dev
    build:
      context: ./services/api_crud
      dockerfile: Dockerfile.dev

    # 🐳 Imagen de Docker utilizada para este servicio
    image: tlaloc-crud:0.1.0

    # 🚀 Comando para iniciar el servidor FastAPI
    command: uvicorn main:app --host 0.0.0.0 --port ${FASTAPI_PORT} --reload

    # 📂 Montaje de volúmenes
    volumes:
      - ./services/api_crud:/app

    # 🏷️ Etiquetas para integración con Traefik
    labels:
      # 🌐 Habilitar Traefik
      traefik.enable: "true"

      # 🌐 Router para FastAPI (HTTP)
      traefik.http.routers.fastapi-router.entrypoints: http
      traefik.http.routers.fastapi-router.rule: Host(`${API_DEV_DOMAIN}`)
      traefik.http.routers.fastapi-router.service: fastapi-service
      traefik.http.services.fastapi-service.loadbalancer.server.port: ${FASTAPI_PORT}

    # 🔄 Política de reinicio
    restart: unless-stopped

    # 📄 Variables de entorno - Modo Desarrollo
    env_file: services/api_crud/.env.dev

    # 🌐 Red asociada
    networks:
      - hic-cibus

# 🌐 Redes utilizadas
networks:
  hic-cibus:
    external: true