services:
  frontend-dev:
    container_name: frontend-dev
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.dev

    # 🐳 Imagen de Docker utilizada para este servicio
    image: tlaloc-frontend:0.1.0

    # 🚀 Comando para iniciar el servidor FastAPI
    command: uvicorn main:app --host 0.0.0.0 --port ${FRONTEND_PORT_DEV} --reload

    # 📂 Montaje de volúmenes
    volumes:
      - ./services/frontend:/app

    # 🏷️ Etiquetas para integración con Traefik
    labels:
      # 🌐 Habilitar Traefik
      traefik.enable: "true"

      # 🌐 Router para FastAPI (HTTP)
      traefik.http.routers.fastapi-router.entrypoints: http
      traefik.http.routers.fastapi-router.rule: Host(`${FRONTEND_DOMAIN_DEV}`)
      traefik.http.routers.fastapi-router.service: fastapi-service
      traefik.http.services.fastapi-service.loadbalancer.server.port: ${FRONTEND_PORT_DEV}

    # 🔄 Política de reinicio
    restart: unless-stopped

    # 🌐 Red asociada
    networks:
      - hic-cibus

    environment:
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN_DEV}

# 🌐 Redes utilizadas
networks:
  hic-cibus:
    external: true