services:
  api_bot-dev:
    container_name: api_bot-dev
    build:
      context: ./services/api_bot
      dockerfile: Dockerfile.dev

    # 🚀 Comando para iniciar la aplicación FastAPI
    command: uvicorn main:app --host 0.0.0.0 --port ${TLALOC_BOT_PORT_DEV} --reload

    # 📂 Montaje de volúmenes
    volumes:
      - ./services/api_bot:/app

    # 🏷️ Etiquetas para integración con Traefik
    labels:
      # 🌐 Habilitar Traefik
      traefik.enable: "true"

      # 🌐 Router para FastAPI (HTTP)
      traefik.http.routers.bot-router.entrypoints: http
      traefik.http.routers.bot-router.rule: Host(`${TLALOC_BOT_DOMAIN_DEV}`)
      traefik.http.routers.bot-router.service: bot-service
      traefik.http.services.bot-service.loadbalancer.server.port: ${TLALOC_BOT_PORT_DEV}

    # 🔄 Política de reinicio
    restart: unless-stopped

    # 📄 Variables de entorno
    env_file: services/api_bot/.env.dev
    environment:
      - API_DOMAIN=${TLALOC_BOT_DOMAIN_DEV}
      - PORT=${TLALOC_BOT_PORT_DEV}


    # 🌐 Red asociada
    networks:
      - hic-cibus

  valkey:
    image: valkey/valkey:7.2.5
    container_name: valkey

    # 🚀 Comando para iniciar Valkey
    command:
      - sh
      - -c
      - |
        valkey-server \
          --save "" \
          --appendonly no \
          --protected-mode yes \
          --requirepass $$VALKEY_PASSWORD

    # 📂 Montaje de volúmenes
    volumes:
      - valkey_data-dev:/data

    # 🗝️ Variables de entorno
    env_file: services/api_bot/.env.dev

    # 🔄 Política de reinicio
    restart: unless-stopped

    # 🌐 Red asociada
    networks:
      - hic-cibus

# 🌐 Redes utilizadas
networks:
  hic-cibus:
    external: true

# 📂 Volúmenes
volumes:
  valkey_data-dev: