# Configuraci칩n de Middlewares
[http.middlewares]

    # Middleware de autenticaci칩n b치sica
    [http.middlewares.auth-basic.basicAuth]
        usersFile = "/etc/traefik/usersFile"

    # Middleware de redirecci칩n a HTTPS
    [http.middlewares.redirect-to-https.redirectScheme]
        scheme = "https"
        permanent = true